apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harshkhare-node-latest
  template:
    metadata:
      labels:
        app: harshkhare-node-latest
    spec:
      containers:
      - name: nodejs-sample-image
        image: $REPOSITORY_URI:$TAG
        imagePullPolicy: Always
        env:
        - name: IMAGE_TAG
          valueFrom:
            configMapKeyRef:
              name: my-app-config
              key: image-tag
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-secret
