apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harshkhare-node-latest
  template:
    metadata:
      labels:
        app: harshkhare-node-latest
    spec:
      containers:
      - name: nodejs-sample-image
        image: 851725513395.dkr.ecr.us-east-1.amazonaws.com/rest-api:${TAG}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"   # Specify CPU request (100 milliCPU)
            memory: "128Mi"   # Specify memory request (128 Megabytes)
          limits:
            cpu: "200m"   # Optionally specify CPU limit
            memory: "256Mi"   # Optionally specify memory limit
        env:
        - name: IMAGE_TAG
          valueFrom:
            configMapKeyRef:
              name: image-tag-config
              key: TAG
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: my-volume
          mountPath: /data  # Mount path in the container
          
      imagePullSecrets:
      - name: dockerhub-secret
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-pvc  # Reference to the PVC
