apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-sample-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harshkhare-node-latest
  template:
    metadata:
      labels:
        app: harshkhare-node-latest
    spec:
      containers:
      - name: nodejs-sample-image
        image: 851725513395.dkr.ecr.us-east-1.amazonaws.com/rest-api:$TAG
        imagePullPolicy: Always
        env:
        - name: IMAGE_TAG
          valueFrom:
            configMapKeyRef:
              name: image-tag-config
              key: TAG
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-secret
