name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: |
        echo Logging in to Amazon ECR....
        aws --version
        # Update the following line with your own region
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}
    
    - name: Build Docker image
      run: |
        echo Build started on $(date)
        echo Building the Docker image...
        COMMIT_HASH=$(echo ${{ github.sha }} | cut -c 1-7)
        TAG=${COMMIT_HASH:-latest}
        echo $TAG
        echo ${{ secrets.CONTAINER_NAME }}
        docker build -t sampleapp:latest .        
        docker tag sampleapp:latest 851725513395.dkr.ecr.us-east-1.amazonaws.com/rest-api:$TAG

   
